### ISSUE TITLE
dual-stack support

### ISSUE THREAD

**Issue by danwinship** [ovn-org/ovn-kubernetes#1142]
Tracking for what needs to be done for dual-stack support.
- Configuration (`pkg/config/`):
  - [x] Allow configuring dual-stack service CIDRs (either via `--secondary-service-cidr` like upstream kube, or via `--service-cidrs`) (#1189)
  - [x] Validate that cluster and service CIDR combination is valid. (ie, either both same-single-stack or both dual-stack) (#1189)
  - [x] Revisit `config.IPv6Mode`. Should we add a parallel `config.IPv4Mode`? Or have `config.IPMode` with `IPv4`, `IPv6`, and `DualStack` options? Note that in many places where we currently check `config.IPv6Mode`, the more dual-stack friendly option is to just look at the IP address currently being operated on and act based on that. (#1189)

- Node startup/configuration (`pkg/node/`):
  - [x] `k8s.ovn.org/l3-gateway-config` annotation needs to allow dual-stack `ip-address` and `next-hop` (#1239)
  - [x] `pkg/node/management-port*.go:createPlatformManagementPort()` needs to configure dual-stack IP/default route and service CIDR route (#1241)
  - [x] `pkg/util/kube.go:GetNodeIP()` doesn't actually need to be dual-stack for the one place it's used (default `ovn-encap-ip`), but it should have a better name in that case (#1461)

- Node management (mostly `pkg/ovn/`):
  - [x] Need dual stack SubnetAllocator support for host subnet/join subnet (#1164)
  - [x] Need to update annotations (`"k8s.ovn.org/node-subnets"`, `"k8s.ovn.org/node-join-subnets"`) to be dual-stack (#1283)
  - [x] `pkg/ovn/ovn.go:WatchNodes()` needs to handle IPv4 and IPv6 host subnets (#1283)
  - [x] `pkg/ovn/master.go:addNode()` needs to allocate and annotate both IPv4 and IPv6 host subnets (#1283)
  - [x] `pkg/ovn/master.go:addNode()` / `ensureNodeLogicalNetwork()` need to configure a single logical switch with information about both IPv4 and IPv6. (#1283)
  - [x] `pkg/ovn/master.go:syncNodeManagementPort()` needs to set up management port for both IPv4 and IPv6 (#1283)
  - [x] `pkg/ovn/master.go:syncGatewayLogicalNetwork()` (#1283)
    - needs to create both IPv4 and IPv6 join subnets
    - needs to add both IPv4 and IPv6 static routes in shared gateway mode
  - [X] `pkg/util/gateway_init.go:GatewayInit()` needs to take, and handle, multiple `joinSubnetStr`, `nicIP`, `defaultGW`, `rampoutIPSubnet` (#1256)
  - [X] `pkg/util/gateway_cleanup.go:GatewayCleanup()` needs to `staticRouteCleanup()` both IPv4 and IPv6 routes (#1256)

- Pods
  - [x] Update the pod annotation (`pkg/util/util.go`, etc) to indicate both IPv4 and IPv6 IPs. (#1129)
  - [x] `pkg/ovn/pods.go:getPodAddresses()` / `waitForPodAddresses()` / `pkg/util/net.go:GetPortAddresses()` need to handle multiple IPs (#1325)
  - [x] `pkg/ovn/pods.go:getRoutesGatewayIP()` needs to return multiple IPs and routes. (Redo it to take a `util.PodAnnotation` object and fill in the gateway/routes fields) (#1325)
  - [x] `pkg/ovn/pods.go:addLogicalPort()`
    - updates for other pods.go and pod annotation changes
    - needs to pass both IPv4 and IPv6 addresses to `lsp-set-addresses` (#1325)
    - needs to pass both IPv4 and IPv6 addresses to `lsp-set-port-security` (#1325)
  - [x] `pkg/ovn/port_cache.go`: needs to handle multiple pod IPs (#1373)

- CNI (`pkg/cni/`):
  - [x] Update the cniserver-to-cnishim communication to include both IPv4 and IPv6 IPs (#1129)
  - [x] Update the cnishim to configure both IPs and return both IPs to kubelet (#1129)
  - [x] `ConfigureInterface` must set both IPs as `external_ids`. (#1129)

- Services. (Note that for services, dual-stack just means allowing both single-stack-IPv4 Services and single-stack-IPv6 Services in the same cluster; no individual Service is itself dual-stack)
  - [x] NodePort handling (eg `createGatewaysVIP`, `handleNodePortLB`) needs to create both IPv4 and IPv6 VIPs, and pick the correct one to use for each Service (#1234)
  - [x] `pkg/node/gateway_localnet.go:localnetAddService()` / `localnetDeleteService()` need to add/delete IPv4 or IPv6 rules depending on the service IP (#1480)
  - [x] `pkg/node/gateway_localnet.go:localnetNodePortWatcher()` needs to set up both iptables and ip6tables base rules (#1480)
  - [x] `pkg/util/gateway_init.go:GetDefaultGatewayRouterIP()`, used by ExternalIP handling, is IPv4-only, but it's also totally broken anyway... (#978)

- NetworkPolicy
  We need separate IPv4 and IPv6 address sets. (The idea about using port groups instead of address sets didn't pan out; `inport` only indicates the ingress port on the current logical switch, so for inter-node traffic we lose the original source port.)
  - [x] `pkg/ovn/namespace.go:addPodToNamespace()` / `deletePodFromNamespace()` / `AddNamespace()` need to check/add/remove multiple IPs from address sets (#1393)
  - [x] `pkg/ovn/common.go` needs to update naming to allow separate IPv4 and IPv6 sets for each namespace (#1393)
  - [x] `pkg/ovn/policy_common.go:getL3MatchFromAddressSet()` needs to match "IPv4-expression || IPv6-expression" (#1393)
  - [x] `pkg/ovn/policy_common.go:ipMatch()` needs to be based on the IP address in question, not the global mode (#1393 / #1428)
  - [x] `pkg/ovn/policy_common.go:addAllowACLFromNode()` needs to allow from both IPv4 or IPv6 address (#1393)

- Unknowns
  - [ ] Any additional fixes necessitated by #889 hybrid overlay
  - [ ] Any additional fixes necessitated by #978 ExternalIP fixes
  - [ ] Any additional fixes necessitated by #1126 cloud loadbalancer iptables rules
  - [ ] Any additional fixes to shared gateway mode after fixing #1141
  - [ ] Any additional fixes necessitated by PRs filed after this issue

cc @dcbw @russellb

**Comment by danwinship** [comment]
(I'm currently working on all the annotation-related stuff.)

**Comment by danwinship** [comment]
doing config stuff now too

**Comment by Billy99** [comment]
@danwinship  Looking into "pkg/ovn/port_cache.go: needs to handle multiple pod IPs" now.

**Comment by Billy99** [comment]
Looking into the remaining "pods" bullet item above.

**Comment by gvbalaji** [comment]
I am looking into these two items under Services
 1. pkg/node/gateway_localnet.go:localnetAddService() / localnetDeleteService() need to add/delete IPv4 or IPv6 rules depending on the service IP
 2. pkg/node/gateway_localnet.go:localnetNodePortWatcher() needs to set up both iptables and ip6tables base rules

**Comment by gvbalaji** [comment]
PR's for these two items under services:
1. pkg/node/gateway_localnet.go:localnetAddService() / localnetDeleteService() need to add/delete IPv4 or IPv6 rules depending on the service IP
2.pkg/node/gateway_localnet.go:localnetNodePortWatcher() needs to set up both iptables and ip6tables base rules

https://github.com/ovn-org/ovn-kubernetes/pull/1326
https://github.com/ovn-org/ovn-kubernetes/pull/1327

**Comment by gvbalaji** [comment]
@danwinship I am planning to look at this item under "NetworkPolicy".

 pkg/ovn/namespace.go:addPodToNamespace() / deletePodFromNamespace() / AddNamespace() need to check/add/remove multiple IPs from address sets

Please let me know if this is ok Or you want me to look at some other policy item first.

**Comment by gvbalaji** [comment]
pkg/ovn/namespace.go:addPodToNamespace() / deletePodFromNamespace() / AddNamespace() need to check/add/remove multiple IPs from address sets is under progress

**Comment by gvbalaji** [comment]
Looking into these items now.
pkg/ovn/policy_common.go:getL3MatchFromAddressSet() needs to match "IPv4-expression || IPv6-expression"
 pkg/ovn/policy_common.go:ipMatch() needs to be based on the IP address in question, not the global mode

@danwinship

**Comment by gvbalaji** [comment]
Additional items I found that needs dual stack support are 
1. hybrid overlay
hybrid-overlay/pkg/controller/master.go :  Method `handleOverlayPort` needs to handle multiple subnets in case of dual stack
hybrid-overlay/pkg/controller/node.go : Method `getNodeSubnetAndIP` needs to handle multiple CIDRs in case of dual stack
pkg/ovn/pods.go : Method `addRoutesGatewayIP`  needs to handle dual stack aspects for hybridOverlayExternalGW.

2. pkg/ovn/gateway_init.go :  Method `gatewayInit` needs to configure multiple IPs for lb_force_snat_ip values
3. pkg/ovn/master.go : Method 'StartClusterMaster' needs to handle  multiple subnets for shared gateway mode

**Comment by danwinship** [comment]
All of the original work is done now... I'm going to update the ipv6 shared gateway bug, and add a new one for hybrid overlay, and we can just fix other things as we find them
